name: Compile and Upload Typst CVs
on: [workflow_dispatch] # [workflow_dispatch, push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Checkout cv.typ template repository
        uses: actions/checkout@v4
        with:
          repository: jskherman/cv.typ
          path: template
      - name: Compile Typst files
        uses: jskherman/typst-action@main
        with:
          source_file: |
            cv.typ
          options: |
            --font-path
            ./fonts
            --root
            .
      - name: Remove README file at docs directory
        run: rm docs/README.md
      - name: Upload PDF files to Cloudflare R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: docs
          destination-dir: docs